name: pocket_guide
description: Get an overview of our product portfolio with the most relevant information
version: 2.1.9+266093
publish_to: none

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  # pubdev version of app_review is not updated anymore. directly linking to git instead
  # to solve iOS dependecies issue.
#  app_review:
#    git:
#       url: https://github.com/fluttercommunity/app_review.git
  blobs: ^2.0.0
  bloc: ^8.1.2
  contentful: ^3.0.5
  contentful_rich_text:
    git:
      url: https://github.com/daian999/contentful-rich-text-flutter.git
  cupertino_icons: ^1.0.6
  dio: ^5.3.2
  dio_smart_retry: ^5.0.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_hooks: ^0.20.3
  flutter_inappwebview: ^5.8.0
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.6.18
  flutter_svg: ^2.0.7
  flutter_web_plugins:
    sdk: flutter
  freezed: ^2.4.5
  freezed_annotation: ^2.4.1
  get_it: ^7.4.1
  go_router: ^5.2.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^0.13.6
  hydrated_bloc: ^9.1.2
  intl: ^0.18.1
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  onetrust_publishers_native_cmp: '^202309.1.0'
  package_info_plus: ^4.1.0
  path_provider: ^2.0.11
  piano_flutter_plugin:
    git:
      url: https://github.com/BASF-Mobile-Solutions/piano_analytics
  shared_preferences: ^2.2.2
  shimmer: ^2.0.0
  url_launcher: ^6.1.14

dev_dependencies:
  bloc_test: ^9.1.4
  build_runner: ^2.4.6
  flutter_gen_runner: ^5.3.1
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  mocktail: ^1.0.1
  very_good_analysis: ^5.1.0

flutter_gen:
  output: lib/core/gen/
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/svgs/
    - assets/icons/
    - assets/documents/HC/pocket_guide_HC_20240506.json
    - assets/documents/HC/pocket_guide_HC_claims_11102023.json
    - assets/documents/HC/pocket_guide_HC_product_type_20240506.json
    - assets/documents/HC/pocket_guide_HC_sustainability_20240506.json
    - assets/documents/Industrial/PocketGuideUpdate-2024-01-19.json
    - assets/documents/Industrial/PocketGuideUpdate_Sustainability_Categories-2024-01-19.json
    - assets/documents/Industrial/PocketGuideUpdate-product_type-2024-01-19.json
